FROM r-base:latest

# Metadata
MAINTAINER "Jhosse Paul Marquez Ruiz" mcromanceva@hotmail.com
LABEL com.beast.version="0.0.1"
LABEL vendor="Kantar MillwardBrown"
LABEL com.beast.release-date="2017-03-29"
LABEL com.beast.is-production="FALSE"

# Environment variables
ENV R_ENV development
ENV NODE_ENV development
ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 7.8.0

# Install root dependencies
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    curl \
    gnupg \
    build-essential

# Set GPG keys to access node repositories
RUN set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    56730D5401028683275BD23C23EFEFE93C4CFFFE \
  ; do \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
  done

# Install node and npm
RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

# Install R packages
RUN R -e "install.packages(c('jsonlite', 'Rserve', 'RSclient'))"

# Start Rserve
CMD R CMD Rserve

